model = "gpt-5-codex"
approval_policy = "on-request"
model_supports_reasoning_summaries = true
sandbox_mode = "workspace-write"
hide_agent_reasoning = true
notify = ["notify_codex.py"]
network_access = true
model_reasoning_effort = "high"


[tools]
web_search = true

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

